[functions.stripe-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/stripe-webhook/deno.json"
entrypoint = "./functions/stripe-webhook/index.ts"

[functions.create-checkout]
enabled = true
verify_jwt = true
import_map = "./functions/create-checkout/deno.json"
entrypoint = "./functions/create-checkout/index.ts"

[functions.manage-stripe-plan]
enabled = true
verify_jwt = true
import_map = "./functions/manage-stripe-plan/deno.json"
entrypoint = "./functions/manage-stripe-plan/index.ts"